#
# /etc/doas.conf
#

# Give users in the wheel group access.
permit persist :adm

# Give root access to other users.
permit nopass root

# Give root access to itself, no password, transparently.
permit nopass keepenv setenv { PATH } root as root

permit nopass :wheel as root cmd /bin/dmesg
permit nopass :adm as root cmd /bin/apk args upgrade --available --prune --no-interactive
